version: "3.8"

services:
    app:
      image: anki-reference-bot-app-image
      container_name: anki-reference-bot-app-container
      build: .
      ports:
        - "80:3000"
      depends_on:
        - postgres
      env_file:
        - .env

    postgres:
      image: postgres:14.1-alpine
      container_name: anki-reference-bot-db-container
      ports:
        - "5440:5432"
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      env_file:
        - .env